from __future__ import annotations

from datetime import datetime
from pathlib import Path
from typing import Any
from xml.sax.saxutils import escape

from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import mm
from reportlab.platypus import (
    PageBreak,
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)


def _safe_text(value: Any, default: str = "Not available") -> str:
    if value is None:
        return default

    text = str(value).strip()
    return escape(text) if text else default


def _percentage(value: Any) -> str:
    try:
        return f"{float(value):.2f}%"
    except (TypeError, ValueError):
        return "Not available"


def generate_ai_release_pdf(report: dict[str, Any], output_path: str | Path) -> Path:
    """
    Generate a professional AI subtitle release report as a PDF.

    Args:
        report: Completed subtitle QA report.
        output_path: Destination path for the generated PDF.

    Returns:
        Path to the generated PDF.
    """

    destination = Path(output_path)
    destination.parent.mkdir(parents=True, exist_ok=True)

    styles = getSampleStyleSheet()

    title_style = ParagraphStyle(
        "ReportTitle",
        parent=styles["Title"],
        fontName="Helvetica-Bold",
        fontSize=21,
        leading=26,
        alignment=TA_CENTER,
        spaceAfter=12,
    )

    section_style = ParagraphStyle(
        "SectionHeading",
        parent=styles["Heading2"],
        fontName="Helvetica-Bold",
        fontSize=13,
        leading=17,
        spaceBefore=10,
        spaceAfter=7,
    )

    body_style = ParagraphStyle(
        "ReportBody",
        parent=styles["BodyText"],
        fontName="Helvetica",
        fontSize=9,
        leading=13,
        spaceAfter=6,
    )

    small_style = ParagraphStyle(
        "SmallText",
        parent=body_style,
        fontSize=8,
        leading=11,
    )

    document = SimpleDocTemplate(
        str(destination),
        pagesize=A4,
        rightMargin=18 * mm,
        leftMargin=18 * mm,
        topMargin=16 * mm,
        bottomMargin=16 * mm,
        title="AI Subtitle Release Report",
        author="AI Subtitle Quality Assurance Agent",
    )

    story: list[Any] = []

    decision = str(
        report.get("final_decision")
        or report.get("overall_status")
        or "REVIEW"
    ).upper()

    executive_summary = report.get("executive_summary", {})
    if not isinstance(executive_summary, dict):
        executive_summary = {}

    story.append(Paragraph("AI Subtitle Release Report", title_style))
    story.append(
        Paragraph(
            "Generated by the AI Subtitle Quality Assurance Agent",
            body_style,
        )
    )
    story.append(Spacer(1, 5 * mm))

    overview_data = [
        ["Release decision", _safe_text(decision)],
        ["Video", _safe_text(report.get("original_video_name"))],
        ["Subtitle file", _safe_text(report.get("original_subtitle_name"))],
        ["Detected language", _safe_text(report.get("language"))],
        ["Language confidence", _percentage(report.get("language_probability"))],
        ["Overall accuracy", _percentage(report.get("overall_score"))],
        ["Speech-text match", _percentage(report.get("text_accuracy"))],
        ["Format score", _percentage(report.get("format_score"))],
        ["Generated", datetime.now().strftime("%d %b %Y, %I:%M %p")],
    ]

    overview_table = Table(
        overview_data,
        colWidths=[52 * mm, 112 * mm],
        repeatRows=0,
    )
    overview_table.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (0, -1), colors.HexColor("#E8EDF5")),
                ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
                ("FONTNAME", (1, 0), (1, -1), "Helvetica"),
                ("FONTSIZE", (0, 0), (-1, -1), 8.5),
                ("TEXTCOLOR", (0, 0), (-1, -1), colors.HexColor("#172033")),
                ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#BCC6D6")),
                ("VALIGN", (0, 0), (-1, -1), "TOP"),
                ("LEFTPADDING", (0, 0), (-1, -1), 7),
                ("RIGHTPADDING", (0, 0), (-1, -1), 7),
                ("TOPPADDING", (0, 0), (-1, -1), 6),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
            ]
        )
    )

    story.append(overview_table)
    story.append(Spacer(1, 6 * mm))

    story.append(Paragraph("Executive Summary", section_style))
    story.append(
        Paragraph(
            _safe_text(
                executive_summary.get("recommendation")
                or report.get("recommendation")
                or report.get("agent_review")
            ),
            body_style,
        )
    )

    story.append(Paragraph("AI Release Assessment", section_style))
    story.append(
        Paragraph(
            _safe_text(report.get("agent_review")),
            body_style,
        )
    )

    story.append(Paragraph("Execution Timeline", section_style))
    execution_trace = report.get("execution_trace", [])

    if isinstance(execution_trace, list) and execution_trace:
        for step in execution_trace:
            story.append(Paragraph(f"• {_safe_text(step)}", body_style))
    else:
        story.append(Paragraph("No execution trace was recorded.", body_style))

    subtitles = report.get("subtitles", [])
    if isinstance(subtitles, list) and subtitles:
        story.append(PageBreak())
        story.append(Paragraph("Subtitle Findings", section_style))

        findings_data = [
            [
                Paragraph("<b>Time</b>", small_style),
                Paragraph("<b>Original subtitle</b>", small_style),
                Paragraph("<b>Suggested subtitle</b>", small_style),
                Paragraph("<b>Match</b>", small_style),
                Paragraph("<b>Status</b>", small_style),
            ]
        ]

        for item in subtitles:
            if not isinstance(item, dict):
                continue

            start = _safe_text(item.get("start"))
            end = _safe_text(item.get("end"))

            findings_data.append(
                [
                    Paragraph(f"{start}<br/>{end}", small_style),
                    Paragraph(_safe_text(item.get("text")), small_style),
                    Paragraph(
                        _safe_text(
                            item.get("suggested_subtitle")
                            or item.get("transcript_text")
                        ),
                        small_style,
                    ),
                    Paragraph(
                        _percentage(
                            item.get("similarity")
                            or item.get("text_accuracy")
                        ),
                        small_style,
                    ),
                    Paragraph(_safe_text(item.get("status")), small_style),
                ]
            )

        findings_table = Table(
            findings_data,
            colWidths=[29 * mm, 43 * mm, 55 * mm, 20 * mm, 19 * mm],
            repeatRows=1,
        )
        findings_table.setStyle(
            TableStyle(
                [
                    ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#263349")),
                    ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
                    ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                    ("FONTSIZE", (0, 0), (-1, -1), 7.5),
                    ("GRID", (0, 0), (-1, -1), 0.45, colors.HexColor("#B9C2D0")),
                    ("VALIGN", (0, 0), (-1, -1), "TOP"),
                    ("ROWBACKGROUNDS", (0, 1), (-1, -1), [
                        colors.white,
                        colors.HexColor("#F5F7FA"),
                    ]),
                    ("LEFTPADDING", (0, 0), (-1, -1), 5),
                    ("RIGHTPADDING", (0, 0), (-1, -1), 5),
                    ("TOPPADDING", (0, 0), (-1, -1), 5),
                    ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
                ]
            )
        )

        story.append(findings_table)

    def add_page_number(canvas: Any, doc: Any) -> None:
        canvas.saveState()
        canvas.setFont("Helvetica", 8)
        canvas.setFillColor(colors.HexColor("#6B7280"))
        canvas.drawRightString(
            A4[0] - 18 * mm,
            9 * mm,
            f"Page {doc.page}",
        )
        canvas.restoreState()

    document.build(
        story,
        onFirstPage=add_page_number,
        onLaterPages=add_page_number,
    )

    return destination